[custom]
; ==========================================
; 1、外部规则集声明
; ==========================================
ruleset=Local-LAN,https://raw.githubusercontent.com/LM-Firefly/Rules/refs/heads/master/Special/Local-LAN.list,type=text
ruleset=SteamCN,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.list,type=clash

[rules]
; ==========================================
; 2、具体分流规则
; ==========================================
rules=DOMAIN,sub-2025.gwshudong.lol,DIRECT
rules=RULE-SET,Local-LAN,DIRECT
rules=RULE-SET,SteamCN,DIRECT
rules=DOMAIN-SUFFIX,cm.steampowered.com,DIRECT
rules=DOMAIN-SUFFIX,steamserver.net,DIRECT
rules=DOMAIN-SUFFIX,steamcontent.com,DIRECT
rules=DOMAIN-SUFFIX,v.smtcdns.net,DIRECT
rules=DOMAIN-SUFFIX,snssdk.com,DIRECT
rules=DOMAIN-SUFFIX,playstation.net,DIRECT
rules=DOMAIN-SUFFIX,cnlang.org,DIRECT
rules=DOMAIN-SUFFIX,atlassian.com,DIRECT
rules=DOMAIN-SUFFIX,download.parallels.com,DIRECT

; 【新增兜底】让其余所有流量走你的默认代理组（通常叫 节点选择、PROXY 或 故障转移）
; 请把下面的“节点选择”四个字，改成你机场订阅里原本那个最主要的策略组名字
rules=MATCH,PROXY
