[custom]
; ==========================================
; 1、直连需要（包含特定域名与调用两个远程文件）
; ==========================================

; 这里的 Local-LAN 和 SteamCN 就是您要调用的两个外部文件
ruleset=Local-LAN,https://raw.githubusercontent.com/LM-Firefly/Rules/refs/heads/master/Special/Local-LAN.list,type=text
ruleset=SteamCN,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.list,type=clash


[rules]
; 以下是您第一部分原本的直连域名列表，转换成订阅器的 [rules] 专用语法：
rules=DOMAIN,sub-2025.gwshudong.lol,DIRECT
rules=RULE-SET,Local-LAN,DIRECT
rules=RULE-SET,SteamCN,DIRECT
rules=DOMAIN-SUFFIX,cm.steampowered.com,DIRECT
rules=DOMAIN-SUFFIX,steamserver.net,DIRECT
rules=DOMAIN-SUFFIX,steamcontent.com,DIRECT
rules=DOMAIN-SUFFIX,v.smtcdns.net,DIRECT
rules=DOMAIN-SUFFIX,snssdk.com,DIRECT
rules=DOMAIN-SUFFIX,playstation.net,DIRECT
rules=DOMAIN-SUFFIX,cnlang.org,DIRECT
rules=DOMAIN-SUFFIX,atlassian.com,DIRECT
rules=DOMAIN-SUFFIX,download.parallels.com,DIRECT
